### ISSUE TITLE
iptables rules after shutdown

### ISSUE THREAD

**Issue by ksurl** [kaysond/trafficjam#5]
what is the state of iptables after the trafficjam container stops running? does it revert all changes written? How would you manually clean up if it crashes and does not write before exiting?

**Comment by kaysond** [comment]
For the sake of security, it leaves all the rules in place. When the container starts, it always does a fresh write of the entire ruleset, then deletes any old rules afterwards. Because of that, any crash could be fixed simply by restarting the container.

As far as manual cleanup to remove all rules, for example, you can always just run `iptables` directly on the host to manipulate/delete the rules as you see fit.

**Comment by ksurl** [comment]
Thanks for clarifying
